# Site settings
title: kmjchaochao
header-img: img/home-bg.jpg
email: Kangmj88@163.com
description: "Just a few posts to share my work with you."
baseurl: ""
url: "kmjchaochao.github.io"
linkedin_username: kmjchaochao
github_username:  kmjchaochao


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
